config/routes.rb
# For details on the DSL available within this file,
# see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: 'notebooks#index'

  devise_for :users
  resources :chunks, only: %i[index show], param: :key
  resources :notebooks
  get '/geojson/:dataset', to: 'geojson#show', constraints: { format: 'json' }
  get '/geojson/:dataset/:level', to: 'geojson#show', constraints: { format: 'json' }
  get '/geojson/:dataset/:level/:like', to: 'geojson#show', constraints: { format: 'json' }
end

app/models/notebook.rb
class Notebook < ApplicationRecord
  belongs_to :user
  has_many :chunks, dependent: :destroy

  after_initialize do
    if new_record?
      self.state_json ||= '{}'
      self.public ||= false
    end
  end

  def state
    JSON.parse(state_json, symbolize_names: true)
  end

  def state=(hash)
    self.state_json = hash.to_json
  end

  def initial_redux_state
    { 'notebook' => as_json.except('state_json') }
      .merge(state.as_json)
  end
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_notebook, only: %i[show edit update destroy]

  # GET /notebooks
  # GET /notebooks.json
  def index
    @notebooks = Notebook.all
  end

  # GET /notebooks/1
  # GET /notebooks/1.json
  def show
    @initial_redux_state = @notebook.initial_redux_state
  end

  # GET /notebooks/new
  def new
    @notebook = Notebook.new
  end

  # GET /notebooks/1/edit
  def edit
  end

  # POST /notebooks
  # POST /notebooks.json
  def create
    @notebook = Notebook.new(notebook_params)

    respond_to do |format|
      if @notebook.save
        format.html {
          redirect_to(@notebook, notice: 'Notebook was successfully created.')
        }
        format.json { render :show, status: :created, location: @notebook }
      else
        format.html { render :new }
        format.json {
          render json: @notebook.errors, status: :unprocessable_entity
        }
      end
    end
  end

  # PATCH/PUT /notebooks/1
  # PATCH/PUT /notebooks/1.json
  def update
    respond_to do |format|
      if @notebook.update(notebook_params)
        format.html {
          redirect_to @notebook, notice: 'Notebook was successfully updated.'
        }
        format.json { render :show, status: :ok, location: @notebook }
      else
        format.html { render :edit }
        format.json {
          render json: @notebook.errors, status: :unprocessable_entity
        }
      end
    end
  end

  # DELETE /notebooks/1
  # DELETE /notebooks/1.json
  def destroy
    @notebook.destroy
    respond_to do |format|
      format.html {
        redirect_to(
          notebooks_url, notice: 'Notebook was successfully destroyed.'
        )
      }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_notebook
      @notebook = Notebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white
    # list through.
    def notebook_params
      params.require(:notebook)
        .permit(:name, :public, :adapter, :pack, :state_json, :user_id)
    end
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/notebooks/_form.html.haml
= form_for @notebook do |f|
  - if @notebook.errors.any?
    #error_explanation
      %h2= "#{pluralize(@notebook.errors.count, "error")} prohibited this notebook from being saved:"
      %ul
        - @notebook.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :public
    = f.check_box :public
  .field
    = f.label :adapter
    = f.text_field :adapter
  .field
    = f.label :pack
    = f.text_field :pack
  .field
    = f.label :state
    = f.text_area :state
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/notebooks/edit.html.haml
%h1 Editing notebook

= render 'form'

= link_to 'Show', @notebook
\|
= link_to 'Back', notebooks_path

app/views/notebooks/index.html.haml
%h1 Listing notebooks

%table
  %thead
    %tr
      %th Name
      %th Public
      %th Adapter
      %th Pack
      %th State
      %th User
      %th
      %th
      %th

  %tbody
    - @notebooks.each do |notebook|
      %tr
        %td= notebook.name
        %td= notebook.public
        %td= notebook.adapter
        %td= notebook.pack
        %td= notebook.state
        %td= notebook.user.name
        %td= link_to 'Show', notebook, data: { turbolinks: 'false' }
        %td= link_to 'Edit', edit_notebook_path(notebook)
        %td= link_to 'Destroy',
          notebook, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Notebook', new_notebook_path

app/views/notebooks/new.html.haml
%h1 New notebook

= render 'form'

= link_to 'Back', notebooks_path

app/views/notebooks/show.html.haml
= content_for :head do
  %meta{ name: 'turbolinks-visit-control', content: 'reload' }
  = javascript_pack_tag @notebook.pack

#state{ data: @initial_redux_state.to_json }