config/routes.rb
# For details on the DSL available within this file,
# see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: 'notebooks#index'

  devise_for :users
  resources :chunks, only: %i[index show], param: :key
  resources :notebooks
  get '/geojson/:dataset', to: 'geojson#show', constraints: { format: 'json' }
  get '/geojson/:dataset/:level', to: 'geojson#show', constraints: { format: 'json' }
  get '/geojson/:dataset/:level/:like', to: 'geojson#show', constraints: { format: 'json' }
end

app/models/chunk.rb
class Chunk < ApplicationRecord
  belongs_to :notebook

  after_destroy do
    begin
      File.delete path
    rescue Exception # rubocop:disable Lint/RescueException
      logger.warn "Warning: failed to delete #{path}".yellow
    end

    begin
      File.delete "#{path}.gz"
    rescue Exception # rubocop:disable Lint/RescueException
      logger.warn "Warning: failed to delete #{path}.gz".yellow
    end
  end

  def to_param
    key
  end

  def path
    "/var/data/storage/#{key}.json"
  end
end

app/controllers/chunks_controller.rb
class ChunksController < ApplicationController
  before_action :set_chunk, only: %i[show]
  # TODO: authenticate user

  # GET /chunks
  # GET /chunks.json
  def index
    @chunks = Chunk.all
  end

  # GET /chunks/1
  # GET /chunks/1.json
  def show
    respond_to do |format|
      format.html {}
      format.json { send_file @chunk.path, disposition: :inline }
    end
  end

  # DELETE /chunks/1
  # DELETE /chunks/1.json
  def destroy
    @chunk.destroy
    respond_to do |format|
      format.html {
        redirect_to chunks_url, notice: 'Chunk was successfully destroyed.'
      }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chunk
      @chunk = Chunk.find_by(key: params[:key])
    end
end

app/helpers/chunks_helper.rb
module ChunksHelper
  def number_to_human_seconds(secs)
    [[60, :sec], [60, :min], [24, :hours], [1000, :days]].map do |count, name|
      if secs&.positive?
        secs, n = secs.divmod(count)
        "#{n.to_i} #{name}"
      end
    end
      .compact.reverse.join(' ')
  end
end

app/views/chunks/_form.html.haml
= form_for @chunk do |f|
  - if @chunk.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chunk.errors.count, "error")} prohibited this chunk from being saved:"
      %ul
        - @chunk.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :size
    = f.number_field :size
  .field
    = f.label :report
    = f.text_field :report
  .actions
    = f.submit 'Save'

app/views/chunks/edit.html.haml
%h1 Editing chunk

= render 'form'

= link_to 'Show', @chunk
\|
= link_to 'Back', chunks_path

app/views/chunks/index.html.haml
%h1 Listing chunks

%table
  %thead
    %tr
      %th id
      %th key
      %th size
      %th time
      %th

  %tbody
    - @chunks.each do |chunk|
      %tr
        %td= chunk.id
        %td= chunk.key
        %td= number_to_human_size(chunk.byte_size)
        %td= number_to_human_seconds(chunk.computation_time)
        %td= link_to 'Show', chunk_path(chunk)

%br

=# link_to 'New Chunk', new_chunk_path

app/views/chunks/new.html.haml
%h1 New chunk

= render 'form'

= link_to 'Back', chunks_path

app/views/chunks/show.html.haml
%p#notice= notice
%p
  %b Key:
  = @chunk.key
%p
  %b Size:
  = @chunk.byte_size
%p
  %b Notebook:
  = @chunk.notebook.id
%p
  %b Computation time:
  = @chunk.computation_time
%pre
  = JSON.pretty_generate(JSON.parse(File.read(@chunk.path)))